---
title: Avinzons.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
baseurl: ''
url: https://avinzons.github.io
markdown: kramdown
remote_theme: artemsheludko/zolan
permalink: pretty
plugins:
- jekyll-remote-theme
post_navigation: true
paginate: 5
include:
- _pages
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
exclude:
- _site
- vendor
- _pages/references.md
- " _pages/references.md"
excerpt_separator: ''
