#-------------------------------
# General Site Settings
title: Alexis Vinzons
header-title: a.v.
logo: #logo.svg # You can add own logo.
description: Alexis Vinzons Portfolio Website


#-------------------------------
# Author Settings
author:
  name: Alexis Vinzons
  image: plusart.jpg
  image-caption: Me at The Met 5th Ave, in front of Carousel State (1968) by Sam Gilliam.
  say-hello: Hello, I’m <strong>Alexis Vinzons</strong>
  bio: I'm a human being who does many things, including design. I'm from New York and I'm a recent grad of Cornell University, where I studied Information Science with a concentration in UX Design, and minors in Dance, and Art History. 
  email: alexisvinzons@yahoo.com

#-------------------------------
# Contact links
contact: false
behance: https://behance.com/alexisvinzons # Add your behance handle
twitter:  # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram:  # Add your Instagram handle



#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: a.vinzons # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: UA-139164903-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

#--------------------------------
exclude:
  - 2016-09-09-DanceFest2016.md
  - 2017-05-22-dailyui.md
  - 2017-06-19-vectorgraphicpractice.md